#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLllV9aj4mFlbgrJTL550gTtBcrxnXP0V/9nI5rgBoZDFIWSHTYHimq9iT87QGjDd/HO16c1EPpnUbq7MilwUiAhadtbzrnCd3tyEJ8EGWRs6CWXIFqKY4Zi8uguWR3xh+u2osfxmfFKQg32iZtez8o5gHETfIQrBP5lH5U8m7idQAH7iNW+/4dLHDwKV5m6wuzPuxG4cVZ4LwID2qL4mynuZrAxwhrrW0LLwmn3gVXLpCs8Iv8xIPkuZQpNvDD1V+oCcb4nwI7AQfPQoaTTMtZbHt83c7m5uKjLSBu5v5FfijpbonmvRKDbNXTbFf4wlK7WGAnxmxPMWfBA+twdNVyJJvlIm+AAnB87DsRlwJ4kvL5gcfAgEFcNqxjaQLA373X8vyW34Lau55wu/MjpzQTzQ921saSEDNsRD/yTFQtI4Z43udrWPvtpL4SL5tglGZdNcL6/1OAriwNzuudtoFXk5GEEbTtItnF7guTfbsUNKN78KVW2rxtcdbjMV77CE= ben@ben-Inspiron-3542
cloud_final_modules:
 - scripts-per-once
packages:
  - openssh-server
  - fail2ban
  - ufw
  - nginx
package_update: true
package_upgrade: true
write_files:
  - content: |
      #!/bin/bash
      curl -fsSL https://cdn.coollabs.io/coolify/install.sh -o /tmp/install.sh
      chmod +x /tmp/install.sh
      /tmp/install.sh
    path: /var/lib/cloud/scripts/per-once/install.sh
    permissions: "0755"
  - path: /etc/nginx/sites-available/hosting.conf
    content: |
      server {
        listen 80;
        listen [::]:80;

        server_name hosting.${domain};

        location / {
            proxy_pass http://localhost:8000;
            include proxy_params;
        }
      }
runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow OpenSSH
  - ufw allow 'Nginx HTTP'
  - ufw allow 'Nginx HTTPS'
  - ufw allow 8000
  - ufw allow 6001
  - ufw enable
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)KbdInteractiveAuthentication/s/^.*$/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)ChallengeResponseAuthentication/s/^.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers devops' /etc/ssh/sshd_config
  - sudo ln -s /etc/nginx/sites-available/hosting.cfg /etc/nginx/sites-enabled/
  - systemctl restart sshd
  - systemctl restart nginx
