- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-certifi
    state: latest

- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc

- name: Check permissions on the GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0444'

- name: Add Docker Repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Download Dokku's GPG key
  ansible.builtin.shell:
    cmd: wget -qO- https://packagecloud.io/dokku/dokku/gpgkey > /etc/apt/trusted.gpg.d/dokku.asc
  args:
    creates: /etc/apt/trusted.gpg.d/dokku.asc

- name: Check permissions on the GPG key
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/dokku.asc
    mode: '0444'

- name: Add Dokku Repository
  apt_repository:
    repo: deb https://packagecloud.io/dokku/dokku/ubuntu/ jammy main
    state: present

- name: Update apt and install Dokku
  apt:
    pkg:
      - dokku
    state: latest

- name: Install Dokku plugins
  shell: dokku plugin:install {{ item.url }} {{ item.name }}
  args:
    creates: /var/lib/dokku/plugins/available/{{ item.name }}
  with_items:
    - { url: "https://github.com/dokku/dokku-letsencrypt.git", name: "letsencrypt" }
    - { url: "https://github.com/dokku/dokku-postgres.git", name: "postgres" }
    - { url: "https://github.com/dokku/dokku-maintenance.git", name: "maintenance" }
    - { url: "https://github.com/dokku/dokku-redis.git", name: "redis" }

- name: Add bash alias (user)
  become: false
  lineinfile:
    path: ~/.bashrc
    line: "alias la='ls -lAh'"
    regexp: '^alias la='

- name: Add bash alias (root)
  lineinfile:
    path: ~/.bashrc
    line: "alias la='ls -lAh'"
    regexp: '^alias la='

## Dokku Configuration
- name: Get Dokku global domain
  ansible.builtin.shell:
    cmd: cat /home/dokku/VHOST
  register: dokku_domain
  changed_when: false

- name: Set Dokku's global domain
  shell: dokku domains:set-global git.flaminghedgehog.com
  changed_when: dokku_domain.stdout != "git.flaminghedgehog.com"

- name: dokku ssh-keys:add for user admin
  shell: echo "{{ lookup('file', 'files/id_rsa.pub') }}" | dokku ssh-keys:add admin
  register: ssh_key_add
  changed_when: ssh_key_add.rc == 0
  failed_when: false

- name: Get Dokku Plugin List
  shell: dokku plugin:list
  register: dokku_plugins
  changed_when: false

- name: Dokku Postgres
  shell: dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres
  when: "'postgres' not in dokku_plugins.stdout"

- name: Dokku CouchDB
  shell: dokku plugin:install https://github.com/dokku/dokku-couchdb.git couchdb
  when: "'couchdb' not in dokku_plugins.stdout"
